### PR TITLE
Add the ability to make resource unit definitions

### PR DESCRIPTION
**Pull request by cheese3660**
This adds a patch manager extension that allows for resource units to be added, and also defines water in terms of liters, sorry @Safarte, you are going to have to rescale your patches again :p

### CODE REVIEW

**Comment by cheese3660** [comment]
Converting to draft as I think its breaking KSP2

**Comment by cheese3660** [comment]
Okay, I will keep this as a draft until the next version of PM is released, as it will require that

**Comment by Falki-git** [comment]
Just pedantics, but can we rename the solution to "CommunityResources" as it might contain other projects in the future?

**Comment by cheese3660** [comment]
Yeah, I could

**Pull request merged**
